fix: sem rel ci

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,112 +2,108 @@ language: python 3.7
 sudo: required
 services:
   - docker
+
+test_stage_reference: &test_stage_ref
+  stage: test &test
+  fast_finish: true
+  before_install:
+    - python --version
+  # command to install dependencies
+    # update docker to edge
+    - sudo apt-get update -y
+    - sudo apt-get install --only-upgrade docker-ce -y
+    - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
+    - export DOCKER_CLI_EXPERIMENTAL=enabled
+    - sudo service docker restart
+    - docker --version
+  install:
+  #  - docker buildx --help
+    #- cd ${TRAVIS_BUILD_DIR}/build
+    # - ./ambianic-build.sh
+    - pip3 install -U codecov
+  # command to run tests
+  script:
+    # fail fast
+    # - set -e
+    # Raspberry PI section
+    # prepare qemu
+    - DEV_TAG=dev-${TAG_SUFFIX}
+    - PROD_TAG=latest-${TAG_SUFFIX}
+    - docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
+    - cat /proc/sys/fs/binfmt_misc/qemu-aarch64
+  #  - docker buildx create --name mybuilder
+  #  - docker buildx use mybuilder
+  #  - docker buildx inspect --bootstrap
+    # setup ARM CPU (raspberry pi) build support
+  #  - >
+  #      if [[ $ARCH =~ "arm" ]]; then
+  #      if [ -z "${ARCH##*arm*}"];  then
+  #        sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
+  #        docker run --rm --privileged multiarch/qemu-user-static:register --reset
+  #      fi
+  #  # build image
+    - cd ${TRAVIS_BUILD_DIR}/build
+    - docker build -f Dev.Dockerfile --platform ${ARCH} -t "ambianic/ambianic-edge:${DEV_TAG}" .
+    - docker tag ambianic/ambianic-edge:${DEV_TAG} "ambianic/ambianic-edge:dev"
+  #  - docker buildx build -f Dev.Dockerfile --platform ${ARCH} -t ambianic/ambianic:dev .
+
+  #  - sudo docker build -f Dev.Dockerfile --platform $ARCH -t ambianic/ambianic:dev --build-arg ARCH=$ARCH .
+    # test image
+  #  - sudo docker run ambianic/ambianic --version
+  #      docker tag ambianic/ambianic ambianic/ambianic:$TAG
+  #      docker push ambianic/ambianic:$TAG
+  #      docker push ambianic/ambianic
+    - docker images
+    - cd $TRAVIS_BUILD_DIR/build
+    - ./ambianic-test.sh
+    # publish binaries
+    - >
+      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
+          echo "ARCH=$ARCH"
+          echo "DEV_TAG=$DEV_TAG"
+          echo "PROD_TAG=$PROD_TAG"
+          pwd
+          ls -al
+
+          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
+          docker push "ambianic/ambianic-edge:${DEV_TAG}"
+          docker manifest create "ambianic/ambianic-edge:dev" "ambianic/ambianic-edge:dev-amd64" "ambianic/ambianic-edge:dev-arm32v7"
+          docker manifest annotate "ambianic/ambianic-edge:dev" "ambianic/ambianic-edge:dev-arm32v7" --os=linux --arch=arm --variant=v7
+          docker manifest annotate "ambianic/ambianic-edge:dev" "ambianic/ambianic-edge:dev-amd64" --os=linux --arch=amd64
+          docker manifest push "ambianic/ambianic-edge:dev"
+
+          cd ${TRAVIS_BUILD_DIR}
+          pwd
+          ls -al
+
+          cp README.md ./src
+
+          docker build -f ./build/Prod.Dockerfile --platform ${ARCH} -t "ambianic/ambianic-edge:${PROD_TAG}" ./src
+          docker tag "ambianic/ambianic-edge:${PROD_TAG}" "ambianic/ambianic-edge:latest"
+          docker push "ambianic/ambianic-edge:${PROD_TAG}"
+          docker manifest create "ambianic/ambianic-edge:latest" "ambianic/ambianic-edge:latest-amd64" "ambianic/ambianic-edge:latest-arm32v7"
+          docker manifest annotate "ambianic/ambianic-edge:latest" "ambianic/ambianic-edge:latest-arm32v7" --os=linux --arch=arm --variant=v7
+          docker manifest annotate "ambianic/ambianic-edge:latest" "ambianic/ambianic-edge:latest-amd64" --os=linux --arch=amd64
+          docker manifest push "ambianic/ambianic-edge:latest"
+      fi
+
+  #        cmd=./semantic-release.sh
+  #        $cmd
+  #        status=$?
+  #        [ $status -eq 0 ] && echo "$cmd command was successful" || echo "$cmd failed"
+  #        echo "Semantic Release completed"
+    - echo $PWD
+    - cd $TRAVIS_BUILD_DIR
+    - ls -al
+  after_success:
+    - codecov # submit code coverage
+
 jobs:
   include:
-    - stage: test
-      matrix:
-            include:
-            - python: 3.7
-              env: ARCH=linux/amd64 TAG_SUFFIX=amd64
-            - python: 3.7
-              env: ARCH=linux/arm/v7 TAG_SUFFIX=arm32v7
-      fast_finish: true
-      before_install:
-        - python --version
-      # command to install dependencies
-        # update docker to edge
-        - sudo apt-get update -y
-        - sudo apt-get install --only-upgrade docker-ce -y
-        - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
-        - export DOCKER_CLI_EXPERIMENTAL=enabled
-        - sudo service docker restart
-        - docker --version
-      install:
-      #  - docker buildx --help
-        #- cd ${TRAVIS_BUILD_DIR}/build
-        # - ./ambianic-build.sh
-        - pip3 install -U codecov
-      # command to run tests
-      script:
-        # fail fast
-        # - set -e
-        # Raspberry PI section
-        # prepare qemu
-        - DEV_TAG=dev-${TAG_SUFFIX}
-        - PROD_TAG=latest-${TAG_SUFFIX}
-        - docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
-        - cat /proc/sys/fs/binfmt_misc/qemu-aarch64
-      #  - docker buildx create --name mybuilder
-      #  - docker buildx use mybuilder
-      #  - docker buildx inspect --bootstrap
-        # setup ARM CPU (raspberry pi) build support
-      #  - >
-      #      if [[ $ARCH =~ "arm" ]]; then
-      #      if [ -z "${ARCH##*arm*}"];  then
-      #        sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
-      #        docker run --rm --privileged multiarch/qemu-user-static:register --reset
-      #      fi
-      #  # build image
-        - cd ${TRAVIS_BUILD_DIR}/build
-        - docker build -f Dev.Dockerfile --platform ${ARCH} -t "ambianic/ambianic-edge:${DEV_TAG}" .
-        - docker tag ambianic/ambianic-edge:${DEV_TAG} "ambianic/ambianic-edge:dev"
-      #  - docker buildx build -f Dev.Dockerfile --platform ${ARCH} -t ambianic/ambianic:dev .
-
-      #  - sudo docker build -f Dev.Dockerfile --platform $ARCH -t ambianic/ambianic:dev --build-arg ARCH=$ARCH .
-        # test image
-      #  - sudo docker run ambianic/ambianic --version
-      #      docker tag ambianic/ambianic ambianic/ambianic:$TAG
-      #      docker push ambianic/ambianic:$TAG
-      #      docker push ambianic/ambianic
-        - docker images
-        - cd $TRAVIS_BUILD_DIR/build
-        - ./ambianic-test.sh
-        # publish binaries
-        - >
-          if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
-              echo "ARCH=$ARCH"
-              echo "DEV_TAG=$DEV_TAG"
-              echo "PROD_TAG=$PROD_TAG"
-              pwd
-              ls -al
-
-              docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
-              docker push "ambianic/ambianic-edge:${DEV_TAG}"
-              docker manifest create "ambianic/ambianic-edge:dev" "ambianic/ambianic-edge:dev-amd64" "ambianic/ambianic-edge:dev-arm32v7"
-              docker manifest annotate "ambianic/ambianic-edge:dev" "ambianic/ambianic-edge:dev-arm32v7" --os=linux --arch=arm --variant=v7
-              docker manifest annotate "ambianic/ambianic-edge:dev" "ambianic/ambianic-edge:dev-amd64" --os=linux --arch=amd64
-              docker manifest push "ambianic/ambianic-edge:dev"
-
-              cd ${TRAVIS_BUILD_DIR}
-              pwd
-              ls -al
-
-              cp README.md ./src
-
-              docker build -f ./build/Prod.Dockerfile --platform ${ARCH} -t "ambianic/ambianic-edge:${PROD_TAG}" ./src
-              docker tag "ambianic/ambianic-edge:${PROD_TAG}" "ambianic/ambianic-edge:latest"
-              docker push "ambianic/ambianic-edge:${PROD_TAG}"
-              docker manifest create "ambianic/ambianic-edge:latest" "ambianic/ambianic-edge:latest-amd64" "ambianic/ambianic-edge:latest-arm32v7"
-              docker manifest annotate "ambianic/ambianic-edge:latest" "ambianic/ambianic-edge:latest-arm32v7" --os=linux --arch=arm --variant=v7
-              docker manifest annotate "ambianic/ambianic-edge:latest" "ambianic/ambianic-edge:latest-amd64" --os=linux --arch=amd64
-              docker manifest push "ambianic/ambianic-edge:latest"
-          fi
-
-      #        cmd=./semantic-release.sh
-      #        $cmd
-      #        status=$?
-      #        [ $status -eq 0 ] && echo "$cmd command was successful" || echo "$cmd failed"
-      #        echo "Semantic Release completed"
-        - echo $PWD
-        - cd $TRAVIS_BUILD_DIR
-        - ls -al
-      after_success:
-        - codecov # submit code coverage
-      #jobs:
-      #  include:
-      #    - stage: docs
-      #      script: ../
-    # Define the release stage that runs semantic-release
+    - <<: *test_stage_ref
+      env: ARCH=linux/amd64 TAG_SUFFIX=amd64
+    - <<: *test_stage_ref
+      env: ARCH=linux/arm/v7 TAG_SUFFIX=arm32v7
     - stage: release
       on:
         branch: master
